apply plugin: 'com.android.library'

group = 'com.github.philjay'

android {
    defaultConfig {
        compileSdk 33
        minSdkVersion 14
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    testOptions {
        unitTests.returnDefaultValues = true
        targetSdk 33// this prevents "not mocked" error
    }
    namespace 'com.github.mikephil.charting'
    lint {
        targetSdk 33
    }
}

dependencies {
    implementation 'androidx.annotation:annotation:1.5.0'
    testImplementation 'junit:junit:4.13.2'
}

task sourcesJar(type: Jar) {
    from android.sourceSets.main.java.srcDirs
    archiveClassifier.set("sources")
}

task javadoc(type: Javadoc) {
    options.charSet = 'UTF-8'
    failOnError false
    source = android.sourceSets.main.java.sourceFiles
    classpath += project.files(androidComponents.sdkComponents.bootClasspath)
}

task javadocJar(type: Jar, dependsOn: javadoc) {
    archiveClassifier.set('javadoc')
    from javadoc.destinationDir
}

artifacts {
    archives sourcesJar
    archives javadocJar
}
